-- Hyprland Lua config (converted from hyprland.conf)
require("hyprland.monitors")
require("hyprland.programs")
require("hyprland.autostart")
require("hyprland.environment")
require("hyprland.permissions")
require("hyprland.look_and_feel")
require("hyprland.input")
require("hyprland.keybindings")
require("hyprland.windows_and_workspaces")
